version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: nginx.dockerfile
    ports:
      - 80:80
    # volumes:
    #   - ./src:/var/www/html
    #   - ./nginx/nginx.conf:etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
  php:
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html
  mysql:
    image: mysql:5.7
    container_name: mysql
    # volumes:
    #    - ./src/dump.sql:docker-entrypoint-initdb.d/dump.sql
