version: "3.8"

services:
  wordpress:
    image: wordpress:php7.3-fpm-alpine
    volumes:
      - $PWD/src:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mysql
      MYSQL_ROOT_PASSWORD: secretpassword
      WORDPRESS_DB_NAME: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: secretpassword
      WORDPRESS_TABLE_PREFIX: wp_
    depends_on: 
      - db
    restart: always
    container_name: wordpress
    links:
      - db
  
  db:
    image: mysql:5.7
    volumes:
      - $PWD/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: secretpassword
      MYSQL_PASSWORD: secretpassword
    container_name: db
    restart: always

  nginx:
    image: nginx
    volumes:
      - $PWD/nginx:/etc/nginx/conf.d/
    ports:
      - 8080:80
    depends_on:
      - wordpress
    links:
    - wordpress
    container_name: nginx
    restart: always
